services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - path: ./.env
        required: false
    expose:
      - 27017
    volumes:
      - ./volumes/mongodb/data/:/data/db/

  tg_bot:
    build:
      context: .
    container_name: tg_bot
    restart: always
    env_file:
      - path: ./.env
        required: false
    depends_on:
      - mongodb
    volumes:
      - ./volumes/tg_bot/logs/:/svo-sked-bot/logs/
